application/vss/vapp/urls.py
from django.urls import path
from . import views

app_name = 'vapp'
urlpatterns = [
    path("", views.index, name='index'),
    path('encrypt/', views.encrypt, name="encrypt"),
    path('verify/', views.verify, name="verify"),
    path('decrypt/', views.decrypt, name="decrypt"),
]

application/vss/vss/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vapp.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_DIR)

application/vss/vapp/models.py
from django.db import models

# Create your models here.

application/vss/vapp/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, 'index.html')


def encrypt(request):
    participants = [
        {"value": 3, "key": "Three"},
        {"value": 4, "key": "Four"},
        {"value": 5, "key": "Five"},
        {"value": 6, "key": "Six"},
        {"value": 7, "key": "Seven"},
        {"value": 8, "key": "Eight"},
        {"value": 9, "key": "Nine"}
    ]

    return render(request, 'encrypt.html', {'participants': participants})


def decrypt(request):
    return render(request, "decrypt.html")


def verify(request):
    return render(request, "verify.html")

application/vss/vapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-md bg-danger navbar-dark mb-5">
        <a class="navbar-brand" href="#">Visual Secret Sharing</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav ml-auto mr-4">
                <li class="nav-item">
                    <a class="nav-link" href="#">Home </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">FAQ</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">User Manual</a>
                </li>
            </ul>

        </div>
    </nav>
    {% block content %}

    {% endblock %}


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>

</html>

application/vss/vapp/templates/decrypt.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
vss decrypt
{% endblock %}

{% block content %}
<div class="card col-md-8 mx-auto shadow-lg p-3 mb-5 bg-white rounded ">
    <h3 class="mt-4 text-center">Please fill the decryption details</h3>
    <form action="#" method="post" class="mt-4 px-3" enctype="multipart/form-data">
    </form>
</div>
{% endblock %}

application/vss/vapp/templates/encrypt.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Encrypt
{% endblock %}

{% block content %}
<script>
    function setThreshold() {
        let threshold = [
            { "value": 2, "key": 'Two' },
            { "value": 3, "key": "Three" },
            { "value": 4, "key": "Four" },
            { "value": 5, "key": "Five" },
            { "value": 6, "key": "Six" },
            { "value": 7, "key": "Seven" },
            { "value": 8, "key": "Eight" },
            { "value": 9, "key": "Nine" }
        ];

        let total_shares = document.getElementById("participants").value;
        let thresholdid = document.getElementById("threshold");
        html = "";
        for (let i = 0; i < total_shares - 2; i++) {
            html += `<option value="${threshold[i].value}">${threshold[i].key}</option>`;
        }
        thresholdid.innerHTML = html;
        let emails = document.getElementById("emails");
        mails = `<div class="form-group">
                <label>Email of participant one</label>
                <input type="email" class="form-control" name="email1" required>
            </div>`;
        for (let i = 0; i < total_shares - 1; i++) {
            mails += `<div class="form-group">
                        <label>Email of participant ${threshold[i].key}</label>
                        <input type="email" class="form-control" name="email${i + 1}" required>
                    </div>`;
        }
        emails.innerHTML = mails;
    }

</script>
<div class="card col-md-8 mx-auto shadow-lg p-3 mb-5 bg-white rounded ">
    <h3 class="mt-4 text-center">Please fill the encryption details</h3>
    <form action="#" method="post" class="mt-4 px-3" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label>Participants</label>
            <select class="form-control" name="participants" id="participants" onChange="setThreshold()">
                {% for participant in participants %}
                <option value="{{participant.value}}">{{participant.key}}</option>
                {% endfor %}
            </select>
        </div>

        <div class="form-group">
            <label>
                Threshold
            </label>
            <select class="form-control" name="threshold" id="threshold">
                <option value="2">Two</option>
            </select>
        </div>
        <div id="emails">
            <div class="form-group">
                <label>Email of participant one</label>
                <input type="email" class="form-control" name="email1" required>
            </div>
            <div class="form-group">
                <label>Email of participant two</label>
                <input type="email" class="form-control" name="email2" required>
            </div>
            <div class="form-group">
                <label>Email of participant three</label>
                <input type="email" class="form-control" name="email3" required>
            </div>
        </div>
        <div class="form-group">
            <label>Image to encrypt</label><br>
            <input type="file" name="image" required>
        </div>
        <input type="submit" class="btn btn-danger mb-4" value="encrypt" />
    </form>
</div>


{% endblock %}

application/vss/vapp/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Visual secreat sharing
{% endblock %}

{% block content %}


<div class="container main">
    <div class="jumbotron mt-5">
        <h1 class="display-4">Be Seured & Safe</h1>
        <p class="lead">Keep the group secrets even more secret with use of visual secrat sharing.</p>
        <hr class="my-4">
        <p>Let's try and get started</p>
        <a class="btn btn-success btn-lg mr-4" href="{% url 'vapp:encrypt' %}" role="button">Encrypt</a>
        <a class="btn btn-info btn-lg" href="{% url 'vapp:verify' %}" role="button">Decrypt</a>
    </div>
</div>
{% endblock %}

application/vss/vapp/templates/verify.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
verify
{% endblock %}

{% block content %}
<div class="card col-md-8 mx-auto shadow-lg p-3 mb-5 bg-white rounded ">
    <h3 class="mt-4 text-center">Please enter the uuid you get while encryption</h3>
    <form action="#" method="post" class="mt-4 px-3">
        <div class="form-group">
            <label>UUID</label>
            <input type="text" name="uuid" class="form-control" required>
        </div>
        <input type="submit" class="btn btn-danger">
    </form>
</div>
<div class="col-md-8 mx-auto ">
    <a href="{% url 'vapp:index' %}" class="btn btn-danger btn-block mt-4 px-4">Back</a>
</div>
{% endblock %}